export GPG_TTY=$(tty)

# Brew
test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)

# Base16 Color Scheme
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

export SAM_CLI_TELEMETRY=0
export ZSH=$HOME/.oh-my-zsh
export FZF_BIN_PATH=/usr/bin/fzf
# export FZF_BIN_PATH="$HOME/.fzf/bin"
export GROFF_NO_SGR=1
export GENDEV=/opt/gendev
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export LOCALBIN="$HOME/.local/bin"
export ESPBIN="$HOME/esp/xtensa-esp32-elf/bin"
export IDF_PATH="$HOME/esp/esp-idf"
export ANDROID_TOOLS_PATH=$HOME/Android/Sdk/platform-tools
export RUST_PATH=$HOME/.cargo/bin
export DART_PUB_PATH=$HOME/.pub-cache/bin
export PATH=$PATH:$HOME/.config/composer/vendor/bin:$HOME/bin:$FZF_BIN_PATH:$ANDROID_TOOLS_PATH:$DART_PUB_PATH
export PATH=$PATH:$LOCALBIN:$GOROOT:$GOBIN:$IDF_PATH:$RUST_PATH
export PATH=$PATH:$LOCALBIN:$GOROOT:$GOBIN:$ESPBIN:$IDF_PATH

export KEYTIMEOUT=1
export JOBS=`nproc`

# ESP/IDF
. $IDF_PATH/export.sh >/dev/null 2>&1

# Latest Golang bins
export PATH=$PATH:/usr/lib/go-1.13/bin

# NVM
export NVM_DIR="${XDG_CONFIG_HOME/:-$HOME/.}.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# NPM
# https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md
NPM_PACKAGES="${HOME}/.npm-packages"
export PATH="$NPM_PACKAGES/bin:$PATH"
# Unset manpath so we can inherit from /etc/manpath via the `manpath` command
unset MANPATH # delete if you already modified MANPATH elsewhere in your config
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

function ttmux() {
    echo "$1"
    tmux -2 detach-client -s $1
    tmux -2 new -A -s $1
}

ZSH_THEME="robbyrussell"

plugins=(
  ssh-agent
  git
  colored-man-pages
  vi-mode
  # npm
  # npx
  F-Sy-H
  fzf
  zsh-z
  zsh-autosuggestions
)

# SSH Agent
zstyle :omz:plugins:ssh-agent identities id_rsa
zstyle :omz:plugins:ssh-agent agent-forwarding yes
zstyle :omz:plugins:ssh-agent lazy yes
zstyle :omz:plugins:ssh-agent quiet yes
zstyle :omz:plugins:ssh-agent helper ksshaskpass

# GitHub auto-complete
fpath=($HOME/.dotfiles/zsh/completions $fpath)
# autoload -U compinit && compinit

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR="vim"
else
  export EDITOR="nvim"
fi

source $ZSH/oh-my-zsh.sh
source $HOME/.dotfiles/zsh/aliases

# Completion for kitty
kitty + complete setup zsh | source /dev/stdin

[ -f ~/.fzf/shell/completion.zsh ] && source ~/.fzf/shell/completion.zsh
[ -f ~/.fzf/shell/key-bindings.zsh ] && source ~/.fzf/shell/key-bindings.zsh

# GO and Dart version managers
[ -f ~/.gvm/scripts/gvm ] && source ~/.gvm/scripts/gvm
[ -f ~/.dvm/scripts/dvm ] && source ~/.dvm/scripts/dvm

# https://github.com/nicodebo/base16-fzf
local color00='#1d1f21'
local color01='#282a2e'
local color02='#373b41'
local color03='#969896'
local color04='#b4b7b4'
local color05='#c5c8c6'
local color06='#e0e0e0'
local color07='#ffffff'
local color08='#cc6666'
local color09='#de935f'
local color0A='#f0c674'
local color0B='#b5bd68'
local color0C='#8abeb7'
local color0D='#81a2be'
local color0E='#b294bb'
local color0F='#a3685a'

export FZF_DEFAULT_OPTS="
  --color=bg+:$color01,bg:$color00,spinner:$color0C,hl:$color0D
  --color=fg:$color04,header:$color0D,info:$color0A,pointer:$color0C
  --color=marker:$color0C,fg+:$color06,prompt:$color0A,hl+:$color0D
"
export FZF_DEFAULT_COMMAND="fd --type f --hidden --follow --exclude .git"
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

bindkey -M vicmd "q" push-line
bindkey -M viins "^_" undo
bindkey '\e[1~' beginning-of-line
bindkey '\e[2~' overwrite-mode
bindkey '\e[3~' delete-char
bindkey '\e[4~' end-of-line

HISTFILE=$HOME/.zsh_history
SAVEHIST=5000
HISTDUP=erase
VI_MODE_RESET_PROMPT_ON_MODE_CHANGE=true
VI_MODE_SET_CURSOR=true
MODE_INDICATOR="%F{cyan}[CMD]%{$reset_color%}"
KEYTIMEOUT=20 #fix 'vv' binding not being triggered

setopt TRANSIENT_RPROMPT
setopt NOBEEP
setopt NOHISTBEEP
setopt APPENDHISTORY
setopt SHAREHISTORY
setopt INCAPPENDHISTORY
setopt BANG_HIST
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_TO_HOME
setopt CORRECT
