# Base16 Color Scheme
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

export ZSH=$HOME/.oh-my-zsh
export FZF_BIN_PATH="$HOME/.fzf/bin"
export GROFF_NO_SGR=1
export GENDEV=/opt/gendev
export GOPATH=$HOME/go
export GOBIN=$GOPATH/bin
export LOCALBIN="$HOME/.local/bin"
export ESPBIN="/opt/esp/xtensa-esp32-elf/bin"
export IDF_PATH="/opt/esp/esp-idf"
export PATH=$PATH:$HOME/.config/composer/vendor/bin:$HOME/bin:$FZF_BIN_PATH
export PATH=$PATH:$LOCALBIN:$GOROOT:$GOBIN:$ESPBIN:$IDF_PATH
export KEYTIMEOUT=1
export JOBS=`nproc`

# NVM
export NVM_DIR="${XDG_CONFIG_HOME/:-$HOME/.}.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# NPM
# https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md
NPM_PACKAGES="${HOME}/.npm-packages"
export PATH="$NPM_PACKAGES/bin:$PATH"
# Unset manpath so we can inherit from /etc/manpath via the `manpath` command
unset MANPATH # delete if you already modified MANPATH elsewhere in your config
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

function ttmux() {
    echo "$1"
    tmux -2 detach-client -s $1
    tmux -2 new -A -s $1
}

ZSH_THEME="robbyrussell"

plugins=(
  git
  colored-man-pages
  vi-mode
  npm
  npx
  fast-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# GitHub auto-complete
fpath=($HOME/.dotfiles/zsh/completions $fpath)
autoload -U compinit && compinit

# Solus eopkg specific completion
autoload bashcompinit
bashcompinit
source /usr/share/bash-completion/completions/eopkg

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR="vim"
else
  export EDITOR="nvim"
fi

source $HOME/.dotfiles/zsh/aliases

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
export FZF_DEFAULT_COMMAND="find -L . -path '*/\.*' -type d -prune -o -type f -print -o -type l -print 2> /dev/null | sed s/^..//"

bindkey -M vicmd "q" push-line
bindkey -M viins "^_" undo
bindkey '\e[1~' beginning-of-line
bindkey '\e[2~' overwrite-mode
bindkey '\e[3~' delete-char
bindkey '\e[4~' end-of-line

HISTFILE=$HOME/.zsh_history
SAVEHIST=5000
HISTDUP=erase
MODE_INDICATOR="%F{cyan}[CMD]%{$reset_color%}"
setopt TRANSIENT_RPROMPT
setopt NOBEEP
setopt NOHISTBEEP
setopt APPENDHISTORY
setopt SHAREHISTORY
setopt INCAPPENDHISTORY
setopt BANG_HIST
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_EXPIRE_DUPS_FIRST
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt HIST_SAVE_NO_DUPS
setopt HIST_REDUCE_BLANKS
setopt HIST_VERIFY
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_TO_HOME
setopt CORRECT
