source /usr/share/defaults/etc/profile

# Android SDK
export ANDROID_HOME=$HOME/Android/Sdk
export PATH=${PATH}:$ANDROID_HOME/tools:$ANDROID_HOME/platform-tools

# Base16 theme
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

eval "base16_tomorrow-night"

# Aliases
if [ -f $HOME/.dotfiles/bash/bash_aliases ]; then
    source $HOME/.dotfiles/bash/bash_aliases
fi

# Completion
if [ -f $HOME/.dotfiles/hub.bash_completion.sh ]; then
    source $HOME/.dotfiles/hub.bash_completion.sh
fi

export GPG_TTY=$(tty)

[ -f $HOME/.fzf.bash ] && source ~/.fzf.bash
